build_from:
  aarch64: n8nio/n8n:stable
  amd64: n8nio/n8n:stable
  armhf: n8nio/n8n:stable
  armv7: n8nio/n8n:stable
  i386: n8nio/n8n:stable
codenotary:
  base_image: codenotary@frenck.dev
  signer: jack@racksync.com