version: 2023.8.1
slug: racksync-autossh-tunnel
name: AutoSSH Tunnel for Home Assistant
description: SSH Tunnel for Home Assistant from RACKSYNC.COM
url: https://github.com/racksync/hass-addons-suite/tree/main/autossh
codenotary: devops@racksync.com
ingress: false
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: system
hassio_api: false
boot: auto
host_network: true
apparmor: true
host_pid: false
homeassistant: 2023.8.1
advanced: true
stage: stable
options: 
  hostname: 'destination-address'
  ssh_port: 22
  username: 'autossh'
  remote_forwarding: 
    - 127.0.0.1:8081:127.0.0.1:8123
  other_ssh_options: '-v'
  force_keygen: false
  note: ""
schema: 
  hostname: str
  ssh_port: int
  username: str
  remote_forwarding: 
    - str
  other_ssh_options: str?
  force_keygen: bool
  note: str?