build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.22
  amd64: ghcr.io/home-assistant/amd64-base:3.22
  armv7: ghcr.io/home-assistant/armv7-base:3.22
codenotary:
  base_image: codenotary@frenck.dev
  signer: devops@racksync.com