name: Replace Repository URL with mono-repo base.
on: [push, pull_request]

jobs:
  replace-hass-addons-cloudflared-tunnel:
    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/checkout@main
     
      - name: Find and Replace
        uses: thiagodnf/string-replacer@v1.0.2
        with:
          find: "github.com/racksync/hass-addons-cloudflared-tunnel"
          replace: "github.com/racksync/hass-addons-suite/tree/main/zerotrust"
          include: |
            zerotrust/**/*.yaml
          exclude: |
            .git/**
            node_modules/**
